# Generated by Django 4.2.3 on 2023-07-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_dog_up_for_adoption_alter_blog_image_alter_dog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='full_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
