# Generated by Django 4.2.3 on 2023-07-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_blog_full_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='full_image',
            field=models.ImageField(default='default_pic.png', upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='default_pic.png', upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='image',
            field=models.ImageField(default='default_pic.png', upload_to='dog_images/'),
        ),
    ]
