# Generated by Django 4.2.3 on 2023-07-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_blog_full_image_alter_blog_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='dog',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='dog_images/'),
        ),
        migrations.AddField(
            model_name='dog',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='dog_images/'),
        ),
    ]
