# Generated by Django 4.2.3 on 2023-07-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_image_dog_image1_dog_image2_dog_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='rescue_story',
            field=models.TextField(default=''),
        ),
    ]
