# Generated by Django 4.2.3 on 2023-07-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_dog_rescue_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='behavior',
            field=models.JSONField(null=True),
        ),
    ]
