# Generated by Django 4.2.3 on 2023-07-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_dog_behavior'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='sterilized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dog',
            name='vaccinated',
            field=models.BooleanField(default=False),
        ),
    ]
